runtime: python39
instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50

entrypoint: python main.py

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "path_to_your_service_account_file.json"

libraries:
- name: flask
  version: latest
- name: google-cloud-pubsub
  version: latest
- name: google-cloud-aiplatform
  version: latest
- name: google-cloud-vision
  version: latest
- name: google-cloud-language
  version: latest
- name: google-cloud-bigquery
  version: latest
- name: googlemaps
  version: latest
